version: "3.4"

services:
  bcp-admin:
    container_name: bcp-admin
    restart: unless-stopped
    build:
      context: src/admin
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
        - REACT_APP_CMS_BASE_URL=${REACT_APP_CMS_BASE_URL}
        - REACT_APP_FRONTEND_BASE_URL=${REACT_APP_FRONTEND_BASE_URL}
        - REACT_APP_KEYCLOAK_AUTH_URL=${REACT_APP_KEYCLOAK_AUTH_URL}
        - REACT_APP_KEYCLOAK_REALM=${REACT_APP_KEYCLOAK_REALM}
        - REACT_APP_KEYCLOAK_CLIENT_ID=${REACT_APP_KEYCLOAK_CLIENT_ID}
        - API_TOKEN=${API_TOKEN}
    env_file: .env
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_CMS_BASE_URL: ${REACT_APP_CMS_BASE_URL}
      REACT_APP_FRONTEND_BASE_URL: ${REACT_APP_FRONTEND_BASE_URL}
      REACT_APP_KEYCLOAK_AUTH_URL: ${REACT_APP_KEYCLOAK_AUTH_URL}
      REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
      API_TOKEN: ${API_TOKEN}
    ports:
      - "8080:3000"
    networks:
      - bcp-cms-network

  bcp-middleware:
    container_name: bcp-middleware
    restart: unless-stopped
    build:
      context: ./src/middleware
      args:
        - ASPNETCORE_ENVIRONMENT=Development
        - API_TOKEN=${API_TOKEN}
        - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
        - REACT_APP_CMS_BASE_URL=${REACT_APP_CMS_BASE_URL}
        - REACT_APP_FRONTEND_BASE_URL=${REACT_APP_FRONTEND_BASE_URL}
        - REACT_APP_KEYCLOAK_AUTH_URL=${REACT_APP_KEYCLOAK_AUTH_URL}
        - REACT_APP_KEYCLOAK_REALM=${REACT_APP_KEYCLOAK_REALM}
        - REACT_APP_KEYCLOAK_CLIENT_ID=${REACT_APP_KEYCLOAK_CLIENT_ID}
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_CMS_BASE_URL: ${REACT_APP_CMS_BASE_URL}
      REACT_APP_FRONTEND_BASE_URL: ${REACT_APP_FRONTEND_BASE_URL}
      REACT_APP_KEYCLOAK_AUTH_URL: ${REACT_APP_KEYCLOAK_AUTH_URL}
      REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
    ports:
      - "5000:5000"
    networks:
      - bcp-cms-network

  bcp-cms:
    image: strapi/strapi:3.5.3
    container_name: bcp-cms
    restart: unless-stopped
    env_file: .env
    build:
      context: src/cms
      args:
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_SSL=${DATABASE_SSL}
        - API_TOKEN=${API_TOKEN}
        - API_USER_NAME=${API_USER_NAME}
        - API_USER_EMAIL=${API_USER_EMAIL}
        - API_USER_PASSWORD=${API_USER_PASSWORD}
        - REACT_APP_CMS_BASE_URL=${REACT_APP_CMS_BASE_URL}
        - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      API_TOKEN: ${API_TOKEN}
      API_USER_NAME: ${API_USER_NAME}
      API_USER_EMAIL: ${API_USER_EMAIL}
      API_USER_PASSWORD: ${API_USER_PASSWORD}
      REACT_APP_CMS_BASE_URL: ${REACT_APP_CMS_BASE_URL}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    networks:
      - bcp-cms-network
    depends_on:
      - postgres
    ports:
      - "1337:1337"

  bcp-staging:
    container_name: bcp-staging
    restart: unless-stopped
    build:
      context: src/web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bcp-cms-network

  postgres:
    image: postgres:13.2
    container_name: bcp-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - bcp-cms-network
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

networks:
  bcp-cms-network:
    driver: bridge

volumes:
  local_postgres_data:
  website:
